"""Automatic migration

Revision ID: 300ed28f75c5
Revises: fa5d7cd8f6a9
Create Date: 2025-05-13 05:01:25.655031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300ed28f75c5'
down_revision = 'fa5d7cd8f6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['us_stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='unique_user_portfolio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
